src/objects/Poker_Game__c.object
<CustomObject>
    <description>Tracks the status and outcome of a game. It is the parent object upon which all other game objects are related.</description>
    <label>Poker Game</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poker Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Poker_Hand__c.object
<CustomObject>
    <description>Related to a game of poker. Each game of poker is made up of multiple hands, which would typically be user stories.</description>
    <fields>
        <fullName>Poker_Game__c</fullName>
        <description>Poker game that the current hand (user story) belongs to.</description>
        <label>Poker Game</label>
        <referenceTo>Poker_Game__c</referenceTo>
        <relationshipLabel>Poker Hands</relationshipLabel>
        <relationshipName>Poker_Hands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Poker Hand</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poker Hands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewGameCmpController.cls
/**
* @author: John Schultz
* @date: 2017-06-13
* @description: Controller for NewGameCmp lightning component.
* @log:
* ----------------------------------------------------------------------------
* Developer       Date          Description
* ----------------------------------------------------------------------------
* John Schultz    2017-06-13    Newly created
*/
public class NewGameCmpController {
	
	/**
	* @author: John Schultz
	* @date: 2017-06-13
	* @description: Creates a new game and returns the newly created record.
	* @param: gameName - String. Name of the new game.
	* @return: Poker_Game__c
	*/
	@AuraEnabled
	public static Poker_Game__c createNewGame(String gameName) {
		return PokerGameService.createNewGame(gameName);
	}
	
	/**
	* @author: John Schultz
	* @date: 2017-07-02
	* @description: Creates a new hand and returns the newly created record.
	* @param: pokerGameId - String. ID of the poker game the hand should belong to.
	* @param: name - String. Name of the user story.
	* @param: position - Decimal. Position of the hand in the game.
	* @return: Poker_Hand__c
	*/
	@AuraEnabled
	public static Poker_Hand__c createNewHand(String pokerGameId, String name, Decimal position) {
		return PokerHandService.createNewHand(pokerGameId, name, position);
	}
	
}