src/objects/Poker_Game__c.object
<CustomObject>
    <description>Tracks the status and outcome of a game. It is the parent object upon which all other game objects are related.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the poker game.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Poker Game</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poker Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Poker_Hand__c.object
<CustomObject>
    <description>Related to a game of poker. Each game of poker is made up of multiple hands, which would typically be user stories.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this the currently active user story that players are estimating?</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Estimates__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine if players can update or cast estimates for this hand.</description>
        <label>Allow Estimates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Final_Estimate__c</fullName>
        <description>The final estimate, either calculated from all player&apos;s estimates or overridden by the game master.</description>
        <label>Final Estimate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Poker_Game__c</fullName>
        <description>Poker game that the current hand (user story) belongs to.</description>
        <label>Poker Game</label>
        <referenceTo>Poker_Game__c</referenceTo>
        <relationshipLabel>Poker Hands</relationshipLabel>
        <relationshipName>Poker_Hands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Position</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Poker Hand</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poker Hands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Poker_Player__c.object
<CustomObject>
    <description>A junction object between a user and a game of poker.</description>
    <fields>
        <fullName>Poker_Game__c</fullName>
        <description>The poker game that this player is currently playing.</description>
        <label>Poker Game</label>
        <referenceTo>Poker_Game__c</referenceTo>
        <relationshipLabel>Poker Players</relationshipLabel>
        <relationshipName>Poker_Players</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user record for this player.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Poker_Players</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Poker Player</label>
    <nameField>
        <label>Poker Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poker Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PokerGameService.cls
/**
* @author: John Schultz
* @date: 2017-06-05
* @description: Service layer for Poker_Game__c object
* @log:
* ----------------------------------------------------------------------------
* Developer       Date          Description
* ----------------------------------------------------------------------------
* John Schultz    2017-06-05    Newly created
*/
public class PokerGameService {
	
	public static final String PENDING_STATUS = 'Pending';
	
	/**
	* @author: John Schultz
	* @date: 2017-06-13
	* @description: Creates a new game and returns the newly created record.
	* @param: gameName - String. Name of the new game.
	* @return: Poker_Game__c
	*/
	public static Poker_Game__c createNewGame(String gameName) {
		Poker_Game__c game = new Poker_Game__c(
			Name = gameName
			, Status__c = PENDING_STATUS
		);
		
		insert game;
		
		return getGameById(game.Id);
	}
	
	/**
	* @author: John Schultz
	* @date: 2017-06-13
	* @description: Method for retrieving game and related records.
	* @param: gameId - String
	* @return: Poker_Game__c
	*/
	public static Poker_Game__c getGameById(String gameId) {
		return
			[SELECT
				Id
				, Status__c
				, Name
				, CreatedById
				, (SELECT
					Id
					, Name
					, Active__c
					, Allow_Estimates__c
					, Position__c
					, Calculated_Average_Estimate__c
					, Consensus_Estimate__c
					, Final_Estimate__c
				FROM Poker_Hands__r
				ORDER BY
					Position__c
					, Name
				)
				, (SELECT
					Id
					, User__c
					, User__r.FirstName
					, User__r.LastName
				FROM Poker_Players__r
				ORDER BY
					User__r.FirstName
				)
			FROM Poker_Game__c
			WHERE Id = :gameId
			LIMIT 1];
	}

}