src/objects/Poker_Game__c.object
<CustomObject>
    <description>Tracks the status and outcome of a game. It is the parent object upon which all other game objects are related.</description>
    <label>Poker Game</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poker Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Poker_Hand__c.object
<CustomObject>
    <description>Related to a game of poker. Each game of poker is made up of multiple hands, which would typically be user stories.</description>
    <fields>
        <fullName>Poker_Game__c</fullName>
        <description>Poker game that the current hand (user story) belongs to.</description>
        <label>Poker Game</label>
        <referenceTo>Poker_Game__c</referenceTo>
        <relationshipLabel>Poker Hands</relationshipLabel>
        <relationshipName>Poker_Hands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Position</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Poker Hand</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Poker Hands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PokerHandService.cls
/**
* @author: John Schultz
* @date: 2017-07-02
* @description: Service class for Poker_Hand__c object.
* @log:
* ----------------------------------------------------------------------------
* Developer       Date          Description
* ----------------------------------------------------------------------------
* John Schultz    2017-07-02    Newly created
*/
public class PokerHandService {
	
	
	/**
	* @author: John Schultz
	* @date: 2017-07-02
	* @description: Method for creating a new poker hand
	* @param: pokerGameId - String. ID of the poker game the hand should belong to.
	* @param: name - String. Name of the user story.
	* @param: position - Decimal. Position of the hand in the game.
	* @return: Poker_Hand__c
	*/
	public static Poker_Hand__c createNewHand(String pokerGameId, String name, Decimal position) {
		Poker_Hand__c hand = new Poker_Hand__c(
			Name = name
			, Poker_Game__c = pokerGameId
			, Position__c = position
		);
		
		insert hand;
		
		return hand;
	}
	
	/**
	* @author: John Schultz
	* @date: 2017-07-04
	* @description: Method for re-sorting the display order of the poker hands (user stories).
	* @param: idToPositionMap - Map<String, Decimal>. Hand record id : position.
	* @return: List<Poker_Hand__c>
	*/
	public static List<Poker_Hand__c> sortHands(Map<String, Decimal> idToPositionMap) {
		List<Poker_Hand__c> hands = new List<Poker_Hand__c>();
		
		for (String handId : idToPositionMap.keySet()) {
			Poker_Hand__c h = new Poker_Hand__c();
			h.Id = handId;
			h.Position__c = idToPositionMap.get(handId);
			
			hands.add(h);
		}
		
		update hands;
		return hands;
	}
	
	
}